version: '2'
services:
  tomcat:
    container_name: my-tomcat
    build:
      context: ../
      dockerfile: ./docker/tomcat/Dockerfile
    ports:
      - "8080:8080"
  mongo:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    container_name: mongo-express
    ports:
      - "8081:8081"
    image: mongo-express
